#ifndef _PAMKIT_CONFIG_H
#define _PAMKIT_CONFIG_H

#define PAMKIT_RESOURCE_DIR "<<SPECIFY>>"

#define TARGET_PAM_MODULE_NAME "pam_unix.so"
#define TARGET_MODULE_COPY_PATH PAMKIT_RESOURCE_DIR "/" TARGET_PAM_MODULE_NAME

#endif /* _PAMKIT_CONFIG_H */
